name: lint
on: [pull_request]
jobs:
  code-ql:
    strategy:
      matrix:
        include:
          - language: java
            buildmode: none
          - language: python
            buildmode: none
    runs-on: "ubuntu-latest"
    timeout-minutes: 120
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.buildmode }}
          queries: +security-and-quality
      - uses: github/codeql-action/analyze@v3
