name: lint
on: [pull_request]
jobs:
  check-opi-format:
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: OPI checker dependencies
        run: python -m pip install -r base/uk.ac.stfc.isis.ibex.opis/requirements.txt
      - name: Run OPI checker
        run: python base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py -strict -directory base/uk.ac.stfc.isis.ibex.opis
      - name: Validate OPIs
        run: python base/uk.ac.stfc.isis.ibex.opis/validate_opis.py

  check-build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Run check_build
        working-directory: ./build
        run: python check_build.py ../base
        
  scriptgenerator-tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: python -m pip install -r ./base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support/requirements.txt
      - name: Run scriptgenerator tests
        working-directory: ./base/uk.ac.stfc.isis.ibex.scriptgenerator/python_support
        run: python -m unittest discover
        
  checkstyle:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: checkstyle
        working-directory: ./base/uk.ac.stfc.isis.ibex.client.tycho.parent
        run: mvn checkstyle:check
  
  code-ql:
    strategy:
      matrix:
        include:
          - language: java
            buildmode: none
          - language: python
            buildmode: none
    runs-on: "ubuntu-latest"
    timeout-minutes: 120
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.buildmode }}
          queries: +security-and-quality
      - uses: github/codeql-action/analyze@v3
